name: Android Build

on:
  push:
    branches: [ "main" ] # Trigger build on pushes to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

  - name: Set up JDK 11
    uses: actions/setup-java@v3
    with:
      java-version: 11
      distribution: 'temurin' 

    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: '21.5.0' # Use your specific Node.js version

    - name: Install dependencies
      run: |
        npm install

    - name: Expo Prebuild
      run: |
        npx expo prebuild -p android

    - name: Build Android Project
      run: |
        cd android
        ./gradlew clean
        ./gradlew assembleRelease 

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk